# Generated by Django 4.2.4 on 2023-08-05 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='text_field',
            new_name='textfield',
        ),
    ]
